const KEYS={pacientes:'saudevax_pacientes',vacinas:'saudevax_vacinas',aplicacoes:'saudevax_aplicacoes'};
let pacientes=load(KEYS.pacientes),vacinas=load(KEYS.vacinas),aplicacoes=load(KEYS.aplicacoes);
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function load(k){try{return JSON.parse(localStorage.getItem(k))||[]}catch{return[]}}
function save(){localStorage.setItem(KEYS.pacientes,JSON.stringify(pacientes));localStorage.setItem(KEYS.vacinas,JSON.stringify(vacinas));localStorage.setItem(KEYS.aplicacoes,JSON.stringify(aplicacoes))}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function digits(v){return v.replace(/\D/g,'')}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function brDate(v){if(!v)return'-';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}
function today(){return new Date().toISOString().slice(0,10)}
function daysUntil(date){const a=new Date(today()+'T00:00:00'),b=new Date(date+'T00:00:00');return Math.ceil((b-a)/86400000)}
function vaccineStatus(v){const dias=daysUntil(v.validade);if(dias<0)return['Vencida','danger'];if(v.quantidade<=v.estoqueMinimo)return['Estoque baixo','warn'];if(dias<=30)return['Vence em breve','warn'];return['Regular','']}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function empty(msg){return `<div class="empty">${msg}</div>`}

$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function go(page){$$('.page').forEach(p=>p.classList.toggle('active',p.id===page));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#pageTitle').textContent={dashboard:'Visão geral',pacientes:'Pacientes',vacinas:'Vacinas e estoque',aplicacoes:'Aplicações'}[page];render()}
$$('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal));$$('.close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});
function openModal(mid){if(mid==='aplicacaoModal')fillVaccineSelect();$('#'+mid).classList.add('open')}

['cpf','telefone','aplicacaoCpf'].forEach(idf=>$('#'+idf).addEventListener('input',e=>e.target.value=digits(e.target.value)));
$('#quantidade').addEventListener('input',e=>{if(+e.target.value<0)e.target.value=0});$('#estoqueMinimo').addEventListener('input',e=>{if(+e.target.value<0)e.target.value=0});

$('#pacienteForm').onsubmit=e=>{e.preventDefault();const err=$('#pacienteError');err.textContent='';try{const cpf=digits($('#cpf').value),nome=$('#nomePaciente').value.trim(),telefone=digits($('#telefone').value),nascimento=$('#nascimento').value;if(cpf.length!==11)throw Error('CPF deve conter exatamente 11 números.');if(!/^[\p{L} .'-]+$/u.test(nome)||nome.length<3)throw Error('Nome deve conter apenas letras e ter pelo menos 3 caracteres.');if(!/^\d{10,11}$/.test(telefone))throw Error('Telefone deve conter 10 ou 11 números.');if(!nascimento)throw Error('Informe a data de nascimento.');if(nascimento>today())throw Error('A data de nascimento não pode estar no futuro.');if(pacientes.some(p=>p.cpf===cpf))throw Error('Já existe um paciente cadastrado com este CPF.');pacientes.push({id:id(),cpf,nome,telefone,nascimento});save();e.target.reset();e.target.closest('.modal').classList.remove('open');render();toast('Paciente cadastrado com sucesso.')}catch(x){err.textContent=x.message}};

$('#vacinaForm').onsubmit=e=>{e.preventDefault();const err=$('#vacinaError');err.textContent='';try{const nome=$('#nomeVacina').value.trim(),fabricante=$('#fabricante').value.trim(),lote=$('#lote').value.trim(),validade=$('#validade').value,quantidade=Number($('#quantidade').value),estoqueMinimo=Number($('#estoqueMinimo').value);if(!nome)throw Error('Informe o nome da vacina.');if(!fabricante)throw Error('Informe o fabricante.');if(!lote)throw Error('Informe o lote.');if(!validade)throw Error('Informe a validade.');if(!Number.isInteger(quantidade)||quantidade<0)throw Error('Quantidade deve ser um número inteiro igual ou maior que zero.');if(!Number.isInteger(estoqueMinimo)||estoqueMinimo<0)throw Error('Estoque mínimo deve ser um número inteiro igual ou maior que zero.');vacinas.push({id:id(),nome,fabricante,lote,validade,quantidade,estoqueMinimo});save();e.target.reset();e.target.closest('.modal').classList.remove('open');render();toast('Vacina cadastrada com sucesso.')}catch(x){err.textContent=x.message}};

$('#aplicacaoForm').onsubmit=e=>{e.preventDefault();const err=$('#aplicacaoError');err.textContent='';try{const cpf=digits($('#aplicacaoCpf').value),vacinaId=$('#aplicacaoVacina').value,profissional=$('#profissional').value.trim(),observacao=$('#observacao').value.trim();if(cpf.length!==11)throw Error('CPF deve conter exatamente 11 números.');const paciente=pacientes.find(p=>p.cpf===cpf);if(!paciente)throw Error('Paciente não encontrado. Cadastre-o antes da aplicação.');const vacina=vacinas.find(v=>v.id===vacinaId);if(!vacina)throw Error('Selecione uma vacina.');if(daysUntil(vacina.validade)<0)throw Error('Esta vacina está vencida e não pode ser aplicada.');if(vacina.quantidade<=0)throw Error('Esta vacina está sem estoque.');if(!/^[\p{L} .'-]+$/u.test(profissional)||profissional.length<3)throw Error('Informe um nome válido para o profissional.');vacina.quantidade-=1;aplicacoes.unshift({id:id(),data:today(),pacienteId:paciente.id,pacienteNome:paciente.nome,cpf:paciente.cpf,vacinaId:vacina.id,vacinaNome:vacina.nome,profissional,observacao});save();e.target.reset();e.target.closest('.modal').classList.remove('open');render();toast('Aplicação registrada e estoque atualizado.')}catch(x){err.textContent=x.message}};

function fillVaccineSelect(){const s=$('#aplicacaoVacina');s.innerHTML='<option value="">Selecione uma vacina</option>'+vacinas.map(v=>`<option value="${v.id}" ${v.quantidade<=0||daysUntil(v.validade)<0?'disabled':''}>${esc(v.nome)} — ${v.quantidade} dose(s)${daysUntil(v.validade)<0?' — vencida':''}</option>`).join('')}
function render(){renderStats();renderPacientes();renderVacinas();renderAplicacoes();fillVaccineSelect()}
function renderStats(){const alertas=vacinas.filter(v=>vaccineStatus(v)[1]).length;$('#statPacientes').textContent=pacientes.length;$('#statDoses').textContent=vacinas.reduce((n,v)=>n+v.quantidade,0);$('#statAplicacoes').textContent=aplicacoes.length;$('#statAlertas').textContent=alertas;const alerts=vacinas.filter(v=>vaccineStatus(v)[1]).slice(0,5);$('#alertList').innerHTML=alerts.length?alerts.map(v=>{const [st,cl]=vaccineStatus(v);return `<div class="list-item"><div><strong>${esc(v.nome)}</strong><small>Lote ${esc(v.lote)} · validade ${brDate(v.validade)}</small></div><span class="status ${cl}">${st}</span></div>`}).join(''):empty('Nenhum alerta de estoque no momento.');$('#recentList').innerHTML=aplicacoes.length?aplicacoes.slice(0,5).map(a=>`<div class="list-item"><div><strong>${esc(a.pacienteNome)}</strong><small>${esc(a.vacinaNome)} · ${brDate(a.data)}</small></div><span class="status">Aplicada</span></div>`).join(''):empty('Nenhuma aplicação registrada ainda.')}
function renderPacientes(){const q=($('#buscaPaciente').value||'').toLowerCase(),list=pacientes.filter(p=>p.nome.toLowerCase().includes(q)||p.cpf.includes(q));$('#pacienteTable').innerHTML=list.length?list.map(p=>`<tr><td><strong>${esc(p.nome)}</strong></td><td>${p.cpf}</td><td>${p.telefone}</td><td>${brDate(p.nascimento)}</td><td><button class="icon-btn" onclick="removePaciente('${p.id}')">Excluir</button></td></tr>`).join(''):`<tr><td colspan="5">Nenhum paciente encontrado.</td></tr>`}
function renderVacinas(){const q=($('#buscaVacina').value||'').toLowerCase(),list=vacinas.filter(v=>[v.nome,v.fabricante,v.lote].some(x=>x.toLowerCase().includes(q)));$('#vacinaTable').innerHTML=list.length?list.map(v=>{const [st,cl]=vaccineStatus(v);return `<tr><td><strong>${esc(v.nome)}</strong><br><small>${esc(v.fabricante)}</small></td><td>${esc(v.lote)}</td><td>${brDate(v.validade)}</td><td>${v.quantidade} <small>/ mín. ${v.estoqueMinimo}</small></td><td><span class="status ${cl}">${st}</span></td><td><button class="icon-btn" onclick="removeVacina('${v.id}')">Excluir</button></td></tr>`}).join(''):`<tr><td colspan="6">Nenhuma vacina encontrada.</td></tr>`}
function renderAplicacoes(){const q=($('#buscaAplicacao').value||'').toLowerCase(),list=aplicacoes.filter(a=>[a.pacienteNome,a.vacinaNome,a.profissional].some(x=>x.toLowerCase().includes(q)));$('#aplicacaoTable').innerHTML=list.length?list.map(a=>`<tr><td>${brDate(a.data)}</td><td><strong>${esc(a.pacienteNome)}</strong><br><small>${a.cpf}</small></td><td>${esc(a.vacinaNome)}</td><td>${esc(a.profissional)}</td><td>${esc(a.observacao||'—')}</td><td><button class="icon-btn" onclick="cancelarAplicacao('${a.id}')">Cancelar</button></td></tr>`).join(''):`<tr><td colspan="6">Nenhuma aplicação encontrada.</td></tr>`}
window.removePaciente=idp=>{if(aplicacoes.some(a=>a.pacienteId===idp))return alert('Este paciente possui aplicações registradas e não pode ser excluído.');if(confirm('Excluir este paciente?')){pacientes=pacientes.filter(p=>p.id!==idp);save();render();toast('Paciente excluído.')}};
window.removeVacina=idv=>{if(aplicacoes.some(a=>a.vacinaId===idv))return alert('Esta vacina possui aplicações registradas e não pode ser excluída.');if(confirm('Excluir esta vacina?')){vacinas=vacinas.filter(v=>v.id!==idv);save();render();toast('Vacina excluída.')}};
window.cancelarAplicacao=ida=>{const a=aplicacoes.find(x=>x.id===ida);if(!a)return;if(confirm('Cancelar esta aplicação? A dose será devolvida ao estoque.')){const v=vacinas.find(x=>x.id===a.vacinaId);if(v)v.quantidade+=1;aplicacoes=aplicacoes.filter(x=>x.id!==ida);save();render();toast('Aplicação cancelada e dose devolvida.')}};
['buscaPaciente','buscaVacina','buscaAplicacao'].forEach(x=>$('#'+x).addEventListener('input',render));render();
